apiVersion: api.scaler.cloudsteak.com/v1alpha1
kind: Scaler
metadata:
  labels:
    app.kubernetes.io/name: scale-operator
    app.kubernetes.io/managed-by: kustomize
  name: scaler-sample
spec:
  # TODO(user): Add fields here
